<div class="container">
    <div class="row px-3">
        <div class="col-lg-10 col-xl-9 card flex-row mx-auto px-0">
            <div class="d-none d-md-flex">
                <div class="container my-5">
                    <div class="row">
                        <i  class="far fa-frown logo404 m-3 ml-5"></i>
                    </div>
                </div>
            </div>
            <div class="card-body">
                <div class="col-lg-10 col-xl-9 card flex-row mx-auto px-0 mt-5 mr-5">
                    <div class="card-body">
                        <h1 class="title text-center mt-4"><b>Oops!</b> Page not found.</h1>
                        <form class="form-box" method="post" action="/home">
                            <div class="mb-3">
                                <button type="submit" class="btn btn-block btn-dark text-uppercase">GO TO HOME PAGE</button>
                            </div>
                        </form>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>