<div class="container">
    <div class="row px-3">
        <div id="login" class="col-xl-5 col-lg-5 col-md-8 card flex-row mx-auto px-0">
            <div class="card-body" v-if="login">
                <h4 class="title text-center mt-2">
                    Sign into your account
                </h4>
                <form class="form-box px-3" method="post" action="/auth">
                    <div class="form-input">
                        <span><i class="fa fa-envelope mt-2 inputIcon"></i></span>
                        <input type="email" name="email" placeholder="Email Address" value="<?= $_SESSION['lastLogged']['email'] ?>" required>
                    </div>
                    <div class="form-input">
                        <span><i class="fa fa-key mt-2 inputIcon"></i></span>
                        <input type="password" name="pass" placeholder="**************" value="<?= $_SESSION['lastLogged']['pass'] ?>" required>
                    </div>

                    <?php
                        switch ($_GET['authCode']) {
                            case 1:
                                echo '<div class="passError">
                                        <i class="fas fa-times mb-2"></i>
                                        Email address or password invalid(s).
                                    </div>';
                                break;
                            case 2:
                                echo '<div class="passError">
                                        <i class="fas fa-times mb-2"></i>
                                        You must to login first.
                                    </div>';
                                break;
                        }
                    ?>

                    <div class="mb-3">
                        <div class="custom-control custom-checkbox">
                            <input type="checkbox" class="custom-control-input" id="cb1" name="remember" <?= ($_SESSION['remember'] === 'on')? 'checked': ''; ?>>
                            <label class="custom-control-label ml-2" for="cb1">Remember me</label>
                        </div>
                    </div>
                    <div class="mb-3">
                        <button id="login" type="submit" class="btn btn-block btn-dark text-uppercase">LOGIN <i class="fas fa-sign-in-alt"></i></button>
                    </div>


                    <div class="text-right mb-1">
                        <a class="forget-link" @click="forgetForm">Forget password?</a>
                    </div>
                    <hr style="background-color: white; width: 80%;">
                    <div class="text-center">
                        Don't have an account?
                        <a id="register" class="register-link" @click="registerForm">Register here</a>
                    </div>
                </form>
            </div>

            <div class="card-body" v-if="register">
                <a @click="loginForm"><i class="fas fa-arrow-left backArrow"></i></a>
                <hr>
                <h4 class="title text-center mt-2">
                    Sign Up
                </h4>
                <form id="registerForm" class="form-box px-3" method="post" action="/register">
                    <div class="form-input">
                        <span><i class="fas fa-user-tag mt-2 inputIcon"></i></span>
                        <input v-model="name" id="name" type="text" placeholder="Complete name" name="name" required>
                    </div>
                    <div class="form-input">
                        <span><i class="fa fa-envelope mt-2 inputIcon"></i></span>
                        <input v-model="email" id="email" type="email" placeholder="Email Address" name="email" required>
                    </div>
                    <div class="form-input">
                        <span><i class="fa fa-key mt-2 inputIcon"></i></span>
                        <input v-model="pass" id="pass" type="password" placeholder="Password" name="pass" :class="{'wrongPassConfirm': errorPass}" required>
                    </div>
                    <div class="form-input">
                        <span><i class="fa fa-key mt-2 inputIcon"></i></span>
                        <input v-model="confirmPass" id="confirmPass" type="password" placeholder="Confirm password" :class="{'wrongPassConfirm': errorPass}" required>
                    </div>
                    <div v-if="errorPass" class="passError">
                        <i class="fas fa-times mb-2"></i>
                        Passwords aren't the same.
                    </div>
                    <div id="birthdate" class="form-input">
                        <span><i class="fas fa-calendar-day mt-2 inputIcon"></i></span>
                        <input v-model="birthdate" id="birthdate" type="date" name="birthdate" required>
                    </div>
                    <div class="custom-control custom-checkbox terms">
                        <input v-model="terms" type="checkbox" class="custom-control-input" id="cb1" name="terms">
                        <label class="custom-control-label mt-4" for="cb1">I accept the terms of service and policy</label>
                    </div>

                    <hr class="mt-5">
                    <div>
                        <button class="btn btn-block btn-dark text-uppercase mt-4" id="signup" type="submit" disabled="disabled">SIGN UP <i class="fas fa-sign-in-alt"></i></button>
                    </div>
                </form>
            </div>

            <div class="card-body w-25" v-if="forget">
                <a @click="loginForm"><i class="fas fa-arrow-left backArrow"></i></a>
                <hr>
                <h4 class="title text-center">
                    Recover password
                </h4>
                <form class="form-box px-3" method="post" action="/recoverPass">
                    <p>First of all, type your email address, will be send an email.</p>
                    <div class="form-input forgetInput">
                        <span><i class="fa fa-envelope mt-2 inputIcon"></i></span>
                        <input type="email" name="email" placeholder="Email Address" required>
                    </div>
                    
                    <hr>
                    <div class="mb-3">
                        <button id="forget" type="submit" id="emailVerification" class="btn btn-block btn-dark text-uppercase" @click="sendEmail">SEND EMAIL</button>
                    </div>
                </form>
            </div>
        </div>
    </div>
</div>