<div class="container">
    <div class="row px-3">
        <div id="home" class="col-lg-10 col-xl-9 card flex-row mx-auto px-0 bg-transparent">
            <div class="card-body" >
                <i class="fas fa-check-circle successLogo"></i>
                <hr>
                <h4 class="title text-center mt-4">
                You have successfully deleted your account.
                </h4>
                <form class="form-box px-3" method="post" action="/">
                    <div class="mb-3">
                        <button type="submit" class="btn btn-block btn-dark text-uppercase">GO TO LOGIN PAGE</button>
                    </div>
                </form>
            </div>
        </div>
    </div>
</div>