<div id="email" class="container">
    <div class="row px-3">
        <div class="col-lg-10 col-xl-9 card flex-row mx-auto px-0 bg-transparent">
            <div class="card-body">
                <i class="fas fa-key successLogo text-dark"></i>
                <hr>
                <h4 class="title text-center mt-4">
                Enter you new password.
                </h4>
                <form class="form-box px-3" method="post" action="/newPass">
                    <div class="form-input">
                    <?php
                        $authCode = isset($_GET['authCode']) ? $_GET['authCode'] : '';
                        $errorPass = ($authCode == 1) ? true : false;
                    ?>
                        <span><i class="fa fa-key mt-2 inputIcon"></i></span>
                        <input class=
                            "<?= ($errorPass) ?'wrongPassConfirm' : '';
                            ?>"
                                type="password" placeholder="Old password" name="oldPass" required>
                            <?= ($errorPass) ? 
                                     '<div class="passError">
                                        <i class="fas fa-times mb-2"></i>
                                        Password incorrect.
                                    </div>' : '';
                            ?>
                    </div>
                    <div class="form-input">
                        <span><i class="fa fa-key mt-2 inputIcon"></i></span>
                        <input v-model="pass" type="password" placeholder="New password" name="pass" :class="{'wrongPassConfirm': errorPass}" required>
                    </div>
                    <div class="form-input">
                        <span><i class="fa fa-key mt-2 inputIcon"></i></span>
                        <input v-model="confirmPass" type="password" placeholder="Confirm password" :class="{'wrongPassConfirm': errorPass}" required>
                    </div>
                    <hr class="mt-2">
                    <div>
                        <button class="btn btn-block btn-dark text-uppercase mt-4" id="continue" type="submit" disabled="disabled">CONTINUE <i class="fas fa-sign-in-alt"></i></button>
                    </div>
                </form>
            </div>
        </div>
    </div>
</div>
